### Revision code on: list, string, tuple, numpy and pandas 

In [2]:
## Swap first and last number in list:

## def funcion:

def swap(x):
    ## how big:
    size = len(x)
    ## swap here, 
    temp = x[0]      ## save so not lost
    x[0] = x[size-1] ## overwrite first
    x[size-1] = temp ## overwrite last
    
    return x

In [3]:
## test:

x = [12,23,34,45,56,67]
print(swap(x))

[67, 23, 34, 45, 56, 12]


In [6]:
# Given a list in Python and provided the positions of the elements, write a program to swap the 
# two elements in the list. 

def swap2(x,y,w): ## positions: x, y, length/vector: w
    temp = w[x]
    w[x]=w[y]
    w[y]=temp
    return w



In [9]:
w = [1,2,3,4,5,6,7,8,9]
print(swap2(0,2,w))

[3, 2, 1, 4, 5, 6, 7, 8, 9]


In [10]:
# How To Find the Length of a List

def count(lis):
    x = len(lis)
    
    return  x

In [12]:
lis = [1,2,3,4,5,6,7,8,9,10]
print(count(lis))

len(lis)

10


10

In [21]:
# Find Maximum of two numbers

def maxi(a,b):
    if a>=b:
        return a
    else:
        return b
    

In [22]:
a=10
b=5

print(maxi(a,b))

10


In [24]:
# Find Minimum of two numbers

def mini(c,d):
    if c<=d:
        return c
    else: 
        return d


In [25]:
print(mini(2,5))

2


In [47]:
# Python program to check whether the string is Symmetrical or Palindrome

## pseudo code:

# find length
# divide in half (iff odd remove middle)
# take the two parts and have two checks
# check1: is sym?: check each entry is same eg [abc] [abc] -> yes
# check2: is palin?: check entry backwards: [abc] [cba] -> yes
# else is neither


# def sorting(s):  ## s is string
#     size = len(s)

#     ## For odd
    
#     if size % 2 != 0: ## check modulo 2
#         half = (size-1)/2
#         ## select the halves:
#         first = s[0:half]
#         second = s[half+1:end]
        
#         for i in 0 : len(first)
#         if first[i] == second[i+len(first)]:
#                 return ('Is symmetric')
#         if first[i] == second[:len(first)-i]:
#                 return ('Is palindrome')
        
#         ## For even:
#     elseif size % 2 = 0:
#         half = size/2
#         ## select the halves:
#         first = s[0:half]
#         second = s[half+1:end]
        
#         for i in 0 : len(first)
#             if first[i] == second[i+len(first)]:
#                 return ('Is symmetric')
#             if first[i] == second[:len(first)-i]:
#                 retun ('Is palindrome')        
        
    
def is_symmetrical_and_palindrome(string):


  # Check if the string is symmetrical.
       if string != string[::-1]:
           return False

       # Check if the string is a palindrome.
       for i in range(len(string) // 2):
            if string[i] != string[len(string) - i - 1]:
                return False

            return True


# Example usage:

string = "oioio"

if is_symmetrical_and_palindrome(string):
    print("The string is symmetrical and a palindrome.")
else:
    print("The string is not symmetrical and a palindrome.")
        
        
    
    
    


The string is symmetrical and a palindrome.


In [50]:
## Reverse words in given string:

string = "one two three four"

## def function:

def rev_string(string):
    ## def empty string:
    reversed_string = ""
    
    ## loop(backwards)
    for i in range(len(string)-1, -1, -1 ):
        ## overwrite empty string
        reversed_string += string[i]
    return reversed_string

reversed_string = rev_string(string)

print(reversed_string)


ruof eerht owt eno


In [55]:
## if want in diff order (rev order):

string = "one two three four"

## split list into chucks of sep words:
words = string.split()

## reverse order now
words.reverse() ## in vector, convert now

rev_string = " ".join(words) ## ensure " " contains a space!

print(rev_string)

four three two one


In [71]:
wordy = 'hello'
new_wordy = wordy[::-2]
print(new_wordy)

olh


In [77]:
## How to Remove Letters From a String (ith letter eg)

string = 'abdcabcd123123'

## remove the a's (replace by nothing: '')
new_str = string.replace('a', '')
print(new_str)

## what if only first a?

new_str2 = string.replace('a', '', 1) ## first occurence
print(new_str2)

## what about chucks of values?

new_str3 = string.replace('123', '', 1)
print(new_str3)

bdcbcd123123
bdcabcd123123
abdcabcd123


In [87]:
## Find length of a string in python

newer_str = 'abcdefgh' # 8 values long
print(len(newer_str))

## or from scratch:

def findlen(newer_str):
    counter = 0
    
    for i in newer_str:
        counter += 1
    return counter
    
print(findlen(newer_str))


8
8


In [95]:
s = 'erqerfqwf'

def count(s):
    counter = 0
    
    for i in s:
        counter += 1
    return counter    

print(count(s))

9


In [116]:
## program to print even length words in a string

name = 'one two three on tw th oner twoo threee'
# newname = name.split()
# print(newname)

def evener(name):
    newname = name.split()
    newer_name = []

    for word in newname:
          if len(word) % 2 == 0:
                newer_name.append(word)  ## append just add the word (of even lenght here)

    return newer_name


# Example usage:
print(evener(name))


['on', 'tw', 'th', 'oner', 'twoo', 'threee']


In [119]:
# Find the size of a Tuple (a collection of objects kinda like a list)

## example tuples: 
Tuple1 = ("A", 1, "B", 2, "C", 3)
Tuple2 = ("Geek1", "Raju", "Geek2", "Nikhil", "Geek3", "Deepanshu")
Tuple3 = ((1, "Lion"), ( 2, "Tiger"), (3, "Fox"), (4, "Wolf"))
 
## (size in therms of memory:)
size = Tuple3.__sizeof__()
print(size)

56


In [122]:
## Maximum and Minimum K elements in Tuple
## k largest/smallesr values, eg (max of) (1,2,3,4,5,6,7,8) k=2-> 7,8

def find_maxmin_k(tuple, k):
    # sort it (ascending)
    sorted_tuple = sorted(tuple)
    
    ## find min/max k elements:
    
    min_k =sorted_tuple[:k] #(position 0 to k)
    max_k =sorted_tuple[-k:] #(kirst k elements from end)
    
    return (min_k, max_k)

tuple = (1,2,3,4,5,3,4,5,43,5,6,5,3,24,543454,0)
k=4
find_maxmin_k(tuple, k)

([0, 1, 2, 3], [6, 24, 43, 543454])

In [127]:
## sum of tuple elements
tuple2 = (1,2,3,4,5,6,7,8,9,10)
tuple3 = (1,[2,3,4,5,6],[7,8],[9,10])

sumtuple = sum(tuple2)
print(sumtuple)

## initialize:
sum=0

for i in tuple3:
    if type(i) == list:
        for j in i:  ## (eg if [2,3,4,5,6], i is 5)
            sum+= j 
    else:
        sum+=i
print(sum)        
        



55
55


In [148]:
## create an empty and a full NumPy array
import numpy as np

empty = np.empty((3,4), dtype = int) ## integer values
print(empty) ## basically really small values (3x4 matrix) if not type = int:

empty2 = np.empty((3,4), dtype = float) ## integer values
print(empty2) ## basically really small values (3x4 matrix) 

fullarray = np.full((3,3), 5, dtype = int) ## 3x3 full of fives
print(fullarray)

fullarray2 = np.full((3,3), 9.9, dtype = float) ## 3x3 full of fives
print(fullarray2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
 [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
 [8.45596650e-307 9.34602321e-307 4.94065646e-322 1.90979621e-312]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[9.9 9.9 9.9]
 [9.9 9.9 9.9]
 [9.9 9.9 9.9]]


In [152]:
# Numpy array filled with all zeros

z = np.zeros(3, dtype = int)
print(z)

a = np.ones(3, dtype = int)
print(a)

[0 0 0]
[1 1 1]


In [157]:
## Replace NumPy array elements that doesn’t satisfy the given condition

n_array = np.array([75,66.7756765456765434,78,7,453,5,325,35,2342342,434,8], dtype = int)
## Replace values greater than 50. with 1
n_array[n_array>50.] = 1
print(n_array)


n_array2 = np.array([[75,66.7756765456765434,78,7,453,5,325,35,2342342,434,8],
                    [75,66.7756765456765434,78,7,453,5,325,35,2342342,434,8]], dtype = int)
## Replace values greater than 50. with 1
n_array2[n_array2<50.] = 1
print(n_array2)

[ 1  1  1  7  1  5  1 35  1  1  8]
[[     75      66      78       1     453       1     325       1 2342342
      434       1]
 [     75      66      78       1     453       1     325       1 2342342
      434       1]]


In [161]:
n_array3 = np.array([[45, 52, 10],
                  [1, 5, 25]])
np.where(n_array3>=5, np.nan, n_array3)

## Replaced all values where the value is = or greater than 5 with NaN

array([[nan, nan, nan],
       [ 1., nan, nan]])

In [170]:
## Maximum value from matrix:

M = np.matrix('[1;2;3;4]') # column
N = np.matrix('[1,2,3,4;1,2,3,4;1,2,3,4]')
print(M)
print(N)
Max = M.max()
Min = M.min()

print(Max, Min)

[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
4 1


In [173]:
## Make a Pandas DataFrame with two-dimensional list

import pandas as pd

lst =[['a','f',15],['b','g',43],['c','h',678],['d','i',34]]

dataframe= pd.DataFrame(lst, columns = ['Tag', 'ID','Number'])
print(dataframe)


  Tag ID  Number
0   a  f      15
1   b  g      43
2   c  h     678
3   d  i      34


In [183]:
## iterating over rows:

# list of dicts
input_df = [{'name':'Sujeet', 'age':10},
            {'name':'Sameer', 'age':11},
            {'name':'Sumit', 'age':12}]

df = pd.DataFrame(input_df)
print(df)

for index, row in df.iterrows(): 
    print(row['name'], row['age'])

     name  age
0  Sujeet   10
1  Sameer   11
2   Sumit   12
Sujeet 10
Sameer 11
Sumit 12


In [188]:
## Create a pandas column using for loop

raw_Data = {'Voter_name': ['Geek1', 'Geek2', 'Geek3', 'Geek4', 
                           'Geek5', 'Geek6', 'Geek7', 'Geek8'], 
            'Voter_age': [15, 23, 25, 9, 67, 54, 42, np.NaN]}
  
df = pd.DataFrame(raw_Data, columns = ['Voter_name', 'Voter_age'])

## which are eligible to vote?
# create list and ammend :
eligible = []

for age in df['Voter_age']:
    if age>=18:
        eligible.append('Yes')
    elif age < 18:
        eligible.append('No')
    else:
        eligible.append('Not Sure')

# Create new column with voter eligibility:

df['Voter'] = eligible

print(df)



  Voter_name  Voter_age     Voter
0      Geek1       15.0        No
1      Geek2       23.0       Yes
2      Geek3       25.0       Yes
3      Geek4        9.0        No
4      Geek5       67.0       Yes
5      Geek6       54.0       Yes
6      Geek7       42.0       Yes
7      Geek8        NaN  Not Sure


In [193]:
## Create a Pandas Series from array (1D labelled array)

data = np.array(['a','b','c','d','e'])

## create the series:
s = pd.Series(data)
print(s)

s = pd.Series(data, index =[1000, 1001, 1002, 1003, 1004])
print(s)





0    a
1    b
2    c
3    d
4    e
dtype: object
1000    a
1001    b
1002    c
1003    d
1004    e
dtype: object


In [206]:
## Basic of Time Series Manipulation
import pandas as pd
from datetime import datetime
import numpy as np
 
# create time series    
range_date = pd.date_range(start ='1/1/2019', end ='1/08/2019',
                                                   freq ='Min')
print(type(range_date[110])) ## value 110 data type timestamp

# convert to dataframe
df = pd.DataFrame(range_date, columns =['date'])
# add new column
df['data'] = np.random.randint(0, 100, size =(len(range_date))) ## adds random data btween 0 and 100
 
print(df.head(10))

<class 'pandas._libs.tslibs.timestamps.Timestamp'>
                 date  data
0 2019-01-01 00:00:00    20
1 2019-01-01 00:01:00    93
2 2019-01-01 00:02:00    93
3 2019-01-01 00:03:00    67
4 2019-01-01 00:04:00    28
5 2019-01-01 00:05:00    18
6 2019-01-01 00:06:00    64
7 2019-01-01 00:07:00    34
8 2019-01-01 00:08:00    63
9 2019-01-01 00:09:00    38


In [207]:
## Convert to string the first 10 time stamps

string_data = [str(x) for x in range_date]
print(string_data[1:11])

['2019-01-01 00:01:00', '2019-01-01 00:02:00', '2019-01-01 00:03:00', '2019-01-01 00:04:00', '2019-01-01 00:05:00', '2019-01-01 00:06:00', '2019-01-01 00:07:00', '2019-01-01 00:08:00', '2019-01-01 00:09:00', '2019-01-01 00:10:00']


In [208]:
## data column converted to datetime
df['datetime'] = pd.to_datetime(df['date'])
# sets index (instead of 0,1,2,3,... its now the time):
# index is a unique identifier for each row in the DataFrame

df = df.set_index('datetime')
# drops date column
df.drop(['date'], axis = 1, inplace = True)
 
print(df['2019-01-05'][1:11])

                     data
datetime                 
2019-01-05 00:01:00    88
2019-01-05 00:02:00    40
2019-01-05 00:03:00    18
2019-01-05 00:04:00    70
2019-01-05 00:05:00    59
2019-01-05 00:06:00    68
2019-01-05 00:07:00     9
2019-01-05 00:08:00    90
2019-01-05 00:09:00    15
2019-01-05 00:10:00    36


C:\Users\Julia\AppData\Local\Temp\ipykernel_29940\2535476333.py:8: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  print(df['2019-01-05'][1:11])
